version: "3.9"
services:
  server:
    image: "coup-app-server"
    container_name: coup-app-server
    build: .
    ports:
      - "8080:8080"
    environment:
      PORT: 8080
      REDIS_URL: redis://redis:6379
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
