version: "3.9"
services:
  server1:
    image: "pray-coup-game"
    container_name: server1
    build: .
    expose:
      - "5000"
    environment:
      PORT: 5000
      REDIS_URL: redis://redis:6379
      NAME: "alibi"
      SEGMENT_WRITE_KEY: 9iaEWlkxkqsQvCExyX2jZvK9jNrZYHDH
  server2:
    image: "pray-coup-game"
    container_name: server2
    build: .
    expose:
      - "5000"
    environment:
      PORT: 5000
      REDIS_URL: redis://redis:6379
      NAME: "blitz"
      SEGMENT_WRITE_KEY: 9iaEWlkxkqsQvCExyX2jZvK9jNrZYHDH
  server3:
    image: "pray-coup-game"
    container_name: server3
    build: .
    expose:
      - "5000"
    environment:
      PORT: 5000
      REDIS_URL: redis://redis:6379
      NAME: "capitao"
      SEGMENT_WRITE_KEY: 9iaEWlkxkqsQvCExyX2jZvK9jNrZYHDH
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "3000:80"
    depends_on:
      - server1
      - server2
